version: '3.8'

services:
  app:
    container_name: gonggoo-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      # 혹시 모를 오타 방지를 위해 환경변수로도 주입 (선택사항이나 추천)
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/gonggoo_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_PASSWORD=password1234
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_COM_GONGGOO=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
  db:
    image: mysql:8.0
    container_name: gonggoo-db
    environment:
      MYSQL_ROOT_PASSWORD: password1234  # application.yml과 일치해야 함
      MYSQL_DATABASE: gonggoo_db         # application.yml과 일치해야 함
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql         # 데이터 영구 저장
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # 한글 설정

  redis:
    image: redis:alpine
    container_name: gonggoo-redis
    ports:
      - "6379:6379"